### ISSUE TITLE
Python 3.10.11 执行报错，以及解决方案

### ISSUE THREAD

**Issue by zuoyangs** [wusuopu/heroes3-cheat#2]
> 
Windows 10 专业版
Python 3.10.11
-------
$ python app.py
Traceback (most recent call last):
  File "D:\worker-python\heroes3-cheat-20230409\app.py", line 7, in <module>
    import bottle
  File "D:\worker-python\heroes3-cheat-20230409\bottle.py", line 87, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\zuoyang\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)

**Comment by zuoyangs** [comment]
> > 
> 
> ## Windows 10 专业版
> Python 3.10.11
> $ python app.py Traceback (most recent call last): File "D:\worker-python\heroes3-cheat-20230409\app.py", line 7, in import bottle File "D:\worker-python\heroes3-cheat-20230409\bottle.py", line 87, in from collections import MutableMapping as DictMixin ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\zuoyang\AppData\Local\Programs\Python\Python310\lib\collections__init__.py)

将 bottle.py 中 from collections import MutableMapping as DictMixin 改成 from collections.abc import MutableMapping as DictMixin 即可。

这两行代码都是能够从 collections 模块导入 MutableMapping 类并将其重命名为 DictMixin。它们的作用类似，但也有一些细微差别。

在 Python 3.3 及更高版本中，collections.abc 模块被引入以替代 collections 模块来定义抽象基类。因此，使用 from collections.abc import MutableMapping as DictMixin 时，您将从正式的抽象基类代码中导入 MutableMapping 类。

在较早的 Python 版本中，您需要从 collections 模块中导入 MutableMapping 类，因为该模块是定义抽象基类的主要位置。但是，如果尝试在 Python 3.3 及更高版本中使用 from collections import MutableMapping as DictMixin，将会受到 DeprecationWarning 警告，这表明您应该改用 from collections.abc import MutableMapping as DictMixin。

综上所述，from collections.abc import MutableMapping as DictMixin 更适合在 Python 3.3 及更高版本中使用。

**Comment by wangxuetoo** [comment]
修改英雄特长后进城镇角色出错
